logger:
  enable: false
  level: info
  format: compact
server:
  port: 3000
  host: http://localhost
  middlewares:
    limit_payload:
      enable: true
      body_limit: 5mb
    logger:
      enable: true
    catch_panic:
      enable: true
    timeout_request:
      enable: true
      timeout: 5000
workers:
  mode: ForegroundBlockingc
mailer:
  smtp:
    enable: true
    host: localhost
    port: 1025
    secure: false
    # auth:
    #   user:
    #   password:
database:
  uri: postgres://loco:loco@localhost:5432/loco_app
  enable_logging: false
  connect_timeout: 500
  idle_timeout: 1000
  min_connections: 1
  max_connections: 1
  auto_migrate: true
  dangerously_truncate: true
  dangerously_recreate: false
redis:
  uri: redis://127.0.0.1/
  dangerously_flush: true
auth:
  secret: PqRwLF2rhHe8J22oBeHy
  expiration: 604800
