[package]
name = "loco-extras"
version = "0.1.0"
description = "Common loco components"
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
async-trait = { workspace = true }
axum = { workspace = true }

[dependencies.loco-rs]
path = "../"
version = "0.3.0"
default-features = true

# initializer
# axum-prometheus = { version = "0.6.1", optional = true }

# initializer
[dependencies.axum-prometheus]
version = "0.6.1"
default-features = false
optional = true

[features]
default = []
full = ["initializer-prometheus"]

initializer-prometheus = ["axum-prometheus"]
